### PR TITLE
Update translation_it.xml

### PR DESCRIPTION
**Pull request by Roby1164**
correction for incorrect string, no title but text   "<text name="CP_help_page_GeneralBase_text"

### CODE REVIEW

**Comment by Tensuko** [comment]
I might was to fast with your PR then, now we have a conflict, can you check to resolve it?

**Comment by Roby1164** [comment]
This string is incorrect in all translations

**Comment by Roby1164** [comment]
with the wording "Title", gives an error, the string must report "Text"
Incorrect: "<text name="CP_help_page_GeneralBase_title"
Correct: "<text name="CP_help_page_GeneralBase_text"

**Comment by Tensuko** [comment]
I will check that, thanks for pointing it out.

**Comment by Tensuko** [comment]
I corrected this for all translations.
Thanks for noticeing it!

**Pull request closed without merging**
