### PR TITLE
fuggo2 translation hu

### PR DESCRIPTION
**Pull request by fuggo2**
I made a translation for the Hungarian language, together with the addition of the basic translation and the novelties, I hope in an acceptable form

### CODE REVIEW

**Comment by Tensuko** [comment]
I don't see a new file in files changed.

**Comment by fuggo2** [comment]
unfortunately i have no idea how i should upload the file, i made it on my computer but i have no idea how i can upload it. I’m neither a programmer nor a developer and I don’t know so much about github what to do, I edited and fixed the xml file. Can you help me with what to do here on github to make it available?

**Comment by pvaiko** [comment]
You have 3 commits here (https://github.com/Courseplay/Courseplay_FS22/pull/1247/commits), don't know what the last two were, but if you just did the first commit (what you did yesterday) it would have been enough.

**Comment by fuggo2** [comment]
> You have 3 commits here (https://github.com/Courseplay/Courseplay_FS22/pull/1247/commits), don't know what the last two were, but if you just did the first commit (what you did yesterday) it would have been enough.

This is the Proper Translation ->  f32c47869ab292a6992c091028d717548638453d

**Comment by Tensuko** [comment]
Why did you delete your own translation file ?
Pls open a new PR for this...
why

**Pull request closed without merging**
