### PR TITLE
Update translation_ru.xml

### PR DESCRIPTION
**Pull request by vitalii2011**

### CODE REVIEW

**Comment by vitalii2011** [comment]
String 236:

fsScreen_2023_06_06_20_05_27

**Comment by Tensuko** [comment]
@Gonimy-Vetrom you may have a look?

**Comment by vitalii2011** [comment]
Try using Crowdin https://crowdin.com/ for translation files.
Eg: 
- https://crowdin.com/project/fs22apalletautoloader 
- https://crowdin.com/project/fsg-mod-assistant
It's easy to work with. Instruction for translators: https://github.com/CitiesSkylinesMods/TMPE/wiki/Localization

**Comment by Gonimy-Vetrom** [comment]
In two hours I can look this

**Comment by Gonimy-Vetrom** [comment]
@vitalii2011 Спасибо за дельную подсказку.
@Tensuko I made the necessary changes. This commit can be closed.

**Comment by Tensuko** [comment]
Thank you!

**Pull request closed without merging**
