### PR TITLE
SelfUnload Not supported in multitools

### PR DESCRIPTION
**Pull request by Lactic68**
More description about the self unload not available in convoy or multitool mode

### CODE REVIEW

**Comment by Lactic68** [comment]
This reference the @Tensuko request in this pull request #816

**Review by pvaiko — CHANGES_REQUESTED** [review]
Could you please make sure there is always a space after the dot.

**Review by Lactic68 — COMMENTED** [review]
Space added after the point.

**Review by pvaiko — APPROVED** [review]
(you know you can have multiple files in the same commit?)

**Pull request merged**
