### PR TITLE
also need for the Combine strawchopper on headland Turns

### PR DESCRIPTION
**Pull request by RealNeo80**
Combine also needs to wait on the headland turns, that it is not spreading out the straw and grassland or roads

### CODE REVIEW

**Comment by Tensuko** [comment]
Did you rly try that ?

**Comment by RealNeo80** [comment]
yep, why? I harvested 5 fields now with this configuration ;)

**Comment by Tensuko** [comment]
So before he starts that turn he discharges the straw ?
But is that rly needed ? I think only on 2nd and more headland since on 1st headland we just drive backwards anyway 1st.

**Comment by RealNeo80** [comment]
yes its standing like on the non-headlands and discharging the straw

needed, in my opinion yes, cause if you drive with a baler afterwards its not easy to drive the curves ;) 
and you have no straw outside the field

**Comment by Tensuko** [comment]
Will not be merged.
Reason:
Combine keeps stopping in the headleand turn, wich makes the turn weird and slow.
There is no benefit for a but straw in a better line.

**Pull request closed without merging**
