### PR TITLE
Update translation_pt.xml

### PR DESCRIPTION
**Pull request by RagagelesOficial**
Total translation into Portuguese correctly

### CODE REVIEW

**Comment by Tensuko** [comment]
Pls keep our formatation...

**Comment by RagagelesOficial** [comment]
Could you help me if I did wrong. It's just that I haven't touched this in a while.

**Comment by Tensuko** [comment]
You changed the text distance. Compare your file with the EN one for example.

**Comment by RagagelesOficial** [comment]
ok, i will compare it with an english file and see how i can improve the translation.

**Comment by RagagelesOficial** [comment]
I hope it's right. I await your reply. Thanks.

**Comment by Tensuko** [comment]
I pushed this in another way as you somehow used your PR for an experiment...
But your name is linked in that push, thanks for your translation :)

**Pull request closed without merging**
