### PR TITLE
Update translation_ru.xml

### PR DESCRIPTION
**Pull request by Gonimy-Vetrom**

### CODE REVIEW

**Comment by Tensuko** [comment]
Thanks for translation, but can we pls stick to out formatation?
Corrected that now.

**Comment by Gonimy-Vetrom** [comment]
Okay. Just because of a large number of spaces, my text does not fit on the screen. :(

**Comment by Tensuko** [comment]
Our translation names might get longer depending on what we will implement, changing all translations after that gives us more work later then.

What text tool do you use ?
I use VS Code or Notepad++ it should automatic scroll to the right if you keep type.

**Comment by Gonimy-Vetrom** [comment]
Notepad++

**Pull request merged**
