### PR TITLE
added missing translation_da 

### PR DESCRIPTION
**Pull request by o0bonde**

### CODE REVIEW

**Comment by o0bonde** [comment]
it happent again... how do i delete all the old commits?

**Comment by Tensuko** [comment]
Don't know how you do this, but should should have a look at how github pull requests work.
Also check out clients like github desktop.
Clone the repository and then make sure the only change from your clone to the main is your translation changes.
You have to rebase your clone to be on the main state.

**Comment by Tensuko** [comment]
Attach the complete translated file here pls, I see what I can do...

**Comment by o0bonde** [comment]
cant upload
cant upload the translation file here,

**Comment by Tensuko** [comment]
change it to .txt then you should be able to

**Comment by o0bonde** [comment]
[translation_da.txt](https://github.com/Courseplay/Courseplay_FS22/files/8495531/translation_da.txt)

**Comment by Tensuko** [comment]
Done.

**Comment by dkfiremann** [comment]
That didn't go well. Seems that all Danish special characters was converted wrong. 
They are also wrong in the txt uploaded. 
Some mismatch with coding?

**Comment by o0bonde** [comment]
I See that to

text without fails:

[translation_da.txt](https://github.com/Courseplay/Courseplay_FS22/files/8496461/translation_da.txt)
.

**Comment by Tensuko** [comment]
Should be fixed now...

**Pull request closed without merging**
