### PR TITLE
Update translation_fr.xml

### PR DESCRIPTION
**Pull request by Lactic68**

### CODE REVIEW

**Review by Lactic68 — COMMENTED** [review]
Some typos corrected

**Review by Lactic68 — COMMENTED** [review]
Corrected labels in coursmanager menu

**Review by Lactic68 — COMMENTED** [review]
Better understanding for the toggle edit mode in coursemanager

**Review by pvaiko — CHANGES_REQUESTED** [review]
Please resolve conflicts

**Review by Lactic68 — COMMENTED** [review]
New FR translations added for Headland directions

**Comment by Lactic68** [comment]
@pvaiko New FR translations added to support headland direction
The resolve conflicts seems not working for me (don't have write access) so I just have created a new review :)

Thank you all for your awesome job !

**Comment by pvaiko** [comment]
> @pvaiko New FR translations added to support headland direction The resolve conflicts seems not working for me (don't have write access) so I just have created a new review :)

We still have conflicts, I think you have to rebase your branch on the current main branch and force push it.

**Comment by Lactic68** [comment]
Closing this request because of conflict

**Pull request closed without merging**
