### PR TITLE
updated ttranslation_da

### PR DESCRIPTION
**Pull request by o0bonde**

### CODE REVIEW

**Comment by pvaiko** [comment]
@Thodor12 something is not right here:
https://github.com/Courseplay/Courseplay_FS22/pull/1077/commits/f39b3768a02f704891046716cd3de81976fa0471

**Comment by Thodor12** [comment]
I think I see the problem, because this was not made in a patch branch but from a fork the code was merged back, this merge caused updates and the changed files looks at all commits pushed at the same time, so it took all the commits beforehand and thinks he changed all translation files.
I'll have a look at it to see if it can only detect changed files authored by the current user

**Comment by o0bonde** [comment]
No clue that happened. i downloaded the main branch. translated the new ting and uploaded the translate_da to my forks an made a pull request.

**Comment by Thodor12** [comment]
@o0bonde Don't worry this has nothing to do with your changes, I created an automated action to update translators. You probably won't have to undertake any action from your side, maybe only reverting those 2 changed files if we ask for it.

**Comment by Thodor12** [comment]
@o0bonde #1078 has just been merged, could you revert the commit made by the actions (essentially just revert last commit) and push that? If applicable also update the translation file in case you missed something or can improve something so we can see the action fire off once more

**Comment by o0bonde** [comment]
delete the pull and make a new?

**Comment by Thodor12** [comment]
> delete the pull and make a new?

If that's easier for you then go ahead

**Comment by Tensuko** [comment]
Yea create a new one pls :)

**Pull request closed without merging**
