### PR TITLE
Update translation_it.xml

### PR DESCRIPTION
**Pull request by Roby1164**

### CODE REVIEW

**Comment by Tensuko** [comment]
You may want to check if there is enough space on the hud for your Shield height offset translation :)

**Comment by Roby1164** [comment]
At this moment I can't check if it enters the Hud, in game.
The problem is that the translation of "offset" is position compensation, I don't know how else to describe it. Or you could abbreviate it to "Compensation." Otherwise we leave the English wording "Offset" hoping that everyone will understand it

**Comment by Tensuko** [comment]
And something like shield hight adjust?
What would that be?

**Comment by Roby1164** [comment]
Let's leave "Offset", since it is a voice understandable by many. At the moment I can't think of anything that could replace it, with a shorter word.
Do you make the correction, or do I have to do the Pull again??

**Comment by Tensuko** [comment]
Better you do this

**Comment by Roby1164** [comment]
ok

**Pull request closed without merging**
