### PR TITLE
Updated trans_da_to_26

### PR DESCRIPTION
**Pull request by o0bonde**

### CODE REVIEW

**Comment by Tensuko** [comment]
Something is wrong there buddy.
Your pull requests keeps say it is a complete change.

**Comment by Tensuko** [comment]
Or better say one of your files must be deleted.
Only keep the on in translation folder and not in main folder (that one just delete).

**Comment by Tensuko** [comment]
Did that for you but we sill have a conflict somehow...

**Comment by o0bonde** [comment]
ich probiere wieder von vorne an.. bin gleich bereit

**Pull request closed without merging**
